version: '2'

services:
    yolov3:
        image: pytorch-yolov3
        build: .
        volumes:
            - .:/srv/app
            - ${OUTPUT_DIR}:/output
            - ${DATA_DIR}:/data
            - ${WEIGHTS_PATH}:/weights
            - ${CONFIG_PATH}:/config
        entrypoint: ["yolov3"]
        stdin_open: true
        tty: true

    download_weights:
        image: pytorch-yolov3
        build: .
        volumes:
            - .:/srv/app
            - ${WEIGHTS_PATH}:/weights
        working_dir: /srv/app/weights
        entrypoint: ["bash", "download_weights.sh"]
        stdin_open: true
        tty: true

    download_coco:
        image: pytorch-yolov3
        build: .
        volumes:
            - .:/srv/app
            - ${DATA_DIR}:/data
        working_dir: /srv/app/data
        entrypoint: ["bash", "get_coco_dataset.sh"]
        stdin_open: true
        tty: true
